### ISSUE TITLE
Are we really going to have more than 1 layer of closures nested?

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/grafana-agent-k8s-operator#107]
Harmonize this in `prometheus_scrape` so we don't need the horrible `_recurse_call_chain` thing.

_Originally posted by @PietroPasotti in https://github.com/canonical/grafana-agent-k8s-operator/pull/95#discussion_r1127761141_

**Comment by rbarry82** [comment]
Actually [done](https://github.com/canonical/prometheus-k8s-operator/pull/465)! It just needs a rebuild of `grafana-agent-k8s` with the new lib.
