### ISSUE TITLE
(machine_charm): create new jobs for each connected target plug

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/grafana-agent-k8s-operator#118]
### Bug Description

- connected snaps show up in $SNAP/shared-logs/PLUGNAME-ID
- when target slots change: create a loki job for each and pass it to loki, NOT a single job for $SNAP/shared-logs/*

### To Reproduce

-

### Environment

-

### Relevant log output

```shell
-
```

**Comment by rbarry82** [comment]
Closed with #124
