### ISSUE TITLE
(machine) Use the `positions_directory` config option

### ISSUE THREAD

**Issue by sed-i** [canonical/grafana-agent-k8s-operator#130]
> I played around a little with this. You can also set a folder in which the grafana-agent will generate its own position files based on the job name so you don't have to set the name manually for every job. There's a field on the same level as "configs" called "positions_directory" (see https://grafana.com/docs/agent/latest/configuration/logs-config/). I had to put it in /var/snap/[...] to get it to work permissions wise, but that did the trick for me at least. Have you considered it?

_Originally posted by @awnns in https://github.com/canonical/grafana-agent-k8s-operator/issues/116#issuecomment-1460315955_

**Comment by simskij** [comment]
Quoting @dstathis; we're already doing this.

**Comment by sed-i** [comment]
Done in #116.
