### ISSUE TITLE
I would have expected the arguments of this method to be the `loki_push_api` URL, with `None` denoting that it has to be dropped. Checking the event type in this method looks clunky.

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/grafana-agent-k8s-operator#15]
I would have expected the arguments of this method to be the `loki_push_api` URL, with `None` denoting that it has to be dropped. Checking the event type in this method looks clunky.

_Originally posted by @mmanciop in https://github.com/canonical/grafana-agent-operator/pull/13#r739203128_

**Comment by rbarry82** [comment]
No longer relevant.
