### ISSUE TITLE
Add support for configuring node-exporter at deploy time 

### ISSUE THREAD

**Issue by marcoppenheimer** [canonical/grafana-agent-k8s-operator#162]
## Problem
- I as a user want to build alert rules for particular services running on my machine-charm, based on various `/proc` and `sysctl` metrics

## Issue
- `node-exporter` provides the ability to make available these metrics, however currently the Grafana Agent Machine subordinate charm does not allow configuration of `node-exporter` at deploy time
- It also isn't clear how one might specify 'Get me the `/proc/$SERVICE_PID/limits` metrics ONLY for specific service pids'. Grabbing them all would be overkill

## Feature Request
- To be able to pass configuration to `node-exporter`, running within the Grafana Agent Machine subordinate, that allows for enabling and configuring additional collectors
    - Assuming that is all that's needed. If not, ALSO that the metrics appear in Grafana and alert rules can be made based on them

- **NICE TO HAVE** - If possible, as the `grafana-agent` charm runs as a subordinate on the same machine, it would be cool if we could have some way of specifying 'grab only metrics for XYZ service pid', maybe with a regex match as it might change?
    - On this, `snap logs` returns something like `2023-03-29T22:39:31+01:00 charmed-kafka.daemon[$SERVICE_PID]:`, maybe that's helpful, maybe not
    - It's possible the `process` collector allows for this, can't tell. It says it's aggregate though which isn't ideal.

## Example Usage
- NOTE - going off of [these disabled by default options](https://github.com/prometheus/node_exporter#disabled-by-default)
- I deploy `grafana-agent`, specifying that I would like to enable `--collector.sysctl` or `--collector.process` or `--collector.sysctl.include=vm.swappiness` and `--collector.sysctl.include=vm.max_map_count`

**Comment by simskij** [comment]
There are two options here:

1. Change the defaults to include more by default
2. Expose a way for charm authors to supply a list of collectors to enable when relating.

**Comment by marcoppenheimer** [comment]
@simskij - Agreed. I think my POV of going for the 2nd option came from an ignorance as to what each collector's metrics looks like. Having it be user-input would allow us to 'figure what we need out'.

If we want to go with option 1, I can probably eye-ball the ones that would be useful to the DP team.

**Comment by rgildein** [comment]
We are working on moving nrpe checks to grafana-agent charm (note: with @simskij we agreed that generic alert rules about principal charm should be part of grafana-agent charm) and here is the list of metrics we are missing so far:

- arp
- bonding
- systemd
- logind
- sysctl
- mdadm
- processes

I think it would be better to provide options to enable any metrics (2nd option), but I'm not sure how related alert rules will be handled. I meant the situation of what happens with alert rules if I enable e.g. "processes", i.e. whether such alert rules will be in Prometheus only when "processes" metrics are enabled or always.

**Comment by simskij** [comment]
I think this should already have been resolved and that this issue just wasn't closed. @marcoppenheimer can you confirm whether you are seeing the sought after metrics now?

**Comment by simskij** [comment]
This was resolved by increasing the amount of collectors enabled in node_exporter by default. Closing this issue without action. If you're still missing something, please go ahead and open a new issue, but given the lack of comments in the issue, it feels fairly safe to assume this is no longer an issue.
