### ISSUE TITLE
[machine] Too many required relations

### ISSUE THREAD

**Issue by dstathis** [canonical/grafana-agent-k8s-operator#200]
### Bug Description

We require grafana-agent to have all of loki-push-api, remote-write, and grafana-dashboard or else we bock. It should instead require only one of those to start working.

### To Reproduce

* Deploy grafana-agent and relate to principal
* Relate to prometheus over remote-write

### Environment

All

### Relevant log output

```shell
-
```

**Comment by Abuelodelanada** [comment]
I'm thinking out loud about this...Now, to have `grafana-agent` machine charm in `ActiveStatus` we need

1. `loki-push-api`, `remote-write` and `grafana-dashboard` relations to be established **OR**
2. `grafana-cloud-config` relation to be established.

But as Dylan pointed out, we may want to only send logs, metrics or dashboards.. :thinking: 

What about having a config in the charm, that let us set the **mode** in which `grafana-agent` is working? For instance: 

- `full observe` (Option `1` or `3`)
- `single observe` (Only one relation to be in `ActiveStatus`)

**Comment by simskij** [comment]
I think it's fine that we say that it's enough with one of them.

We could update the ActiveStatus with a message about which ones are disabled, like: `Metrics: off` or `Metrics & Dashboards: off`.
