### ISSUE TITLE
Pydantic module not found warning deploying Grafana-Agent machine charm

### ISSUE THREAD

**Issue by kian99** [canonical/grafana-agent-k8s-operator#209]
### Bug Description

When deploying this [guide](https://charmhub.io/topics/canonical-observability-stack/tutorials/instrumenting-machine-charms) to instrument a machine charm, when deploying the Grafana Agent subordinate charm, the output of `juju debug-log` shows warnings indicating that in the **provider** charm there is a missing library for Pydantic.
The requiring charm used in this case did have Pydantic and cosl in its requirements.txt

### To Reproduce

In one terminal
1. `juju debug-log`
In another
1. `juju bootstrap lxd
2. `juju add-model test
3. `juju deploy ./<local-charm-with-cos-relation>
4. `juju deploy grafana-agent --channel edge
5. `juju relate <my-app>:cos-agent grafana-agent
Observer warnings in juju debug-log

### Environment

grafana agent charm - channel=edg, rev=10
```
juju --version
2.9.43-ubuntu-amd64
```
```
lxc --version
5.14
```

### Relevant log output

```shell
unit-canonical-livepatch-server-0: 13:52:21 INFO juju.worker.uniter.operation ran "cos-agent-relation-created" hook (via hook dispatching script: dispatch)
unit-grafana-agent-0: 13:52:21 WARNING unit.unit-grafana-agent-0.meter-status-changed Traceback (most recent call last):
unit-grafana-agent-0: 13:52:21 WARNING unit.unit-grafana-agent-0.meter-status-changed   File "./src/charm.py", line 14, in <module>
unit-grafana-agent-0: 13:52:21 WARNING unit.unit-grafana-agent-0.meter-status-changed     from charms.grafana_agent.v0.cos_agent import COSAgentRequirer
unit-grafana-agent-0: 13:52:21 WARNING unit.unit-grafana-agent-0.meter-status-changed   File "/var/lib/juju/agents/unit-grafana-agent-0/charm/lib/charms/grafana_agent/v0/cos_agent.py", line 171, in <module>
unit-grafana-agent-0: 13:52:21 WARNING unit.unit-grafana-agent-0.meter-status-changed     import pydantic
unit-grafana-agent-0: 13:52:21 WARNING unit.unit-grafana-agent-0.meter-status-changed ModuleNotFoundError: No module named 'pydantic'
```

**Comment by sed-i** [comment]
This is surprising, as pydantic is listed in both `requirements.txt` and PYDEPS.
Will investigate.
