### ISSUE TITLE
Allow COSAgentProvider to dynamically change alert rules / scrape job

### ISSUE THREAD

**Issue by chanchiwai-ray** [canonical/grafana-agent-k8s-operator#212]
### Enhancement Proposal

Currently, the `COSAgentProvider` only allow us to specify the `metrics_endpoints` and `metrics_rules_dir` when initializing the class. To change them, we might have to re-initializing the class with different values. This is not so convenient to when some charms that need to dynamically change the `metrics_endpoints` or `metrics_rules_dir`. For example, a charm may offer a config option to change the port of the `metrics_endpoints`, or a charm may not need all the alert rules defined in `metrics_rules_dir` (some exporter can enable / disable collectors, so the not all the alert rules are relevant).

So, it will be nice to consider having a public function to dynamically change the `metrics_endpoints` and `metrics_rules_dir`. For `metrics_rules_dir`, it might be worth to consider having a more granular control of what alert rules in the `metrics_rules_dir` should be included. 

Thank you

**Comment by sed-i** [comment]
Hi @chanchiwai-ray,
It sounds like you're interested in having the built-in alert rules dynamic, rather than static, i.e. [this kind of functionality](https://github.com/canonical/cos-configuration-k8s-operator/blob/c4f6dc2375825c13eeb5c731f49d4f42155e3c34/lib/charms/prometheus_k8s/v0/prometheus_scrape.py#L1862) in cos-agent.
- Would you mind elaborating the use case?
- Have you considered [cos-config](https://github.com/canonical/cos-configuration-k8s-operator)?

**Comment by chanchiwai-ray** [comment]
> It sounds like you're interested in having the built-in alert rules dynamic, rather than static, i.e. [this kind of functionality](https://github.com/canonical/cos-configuration-k8s-operator/blob/c4f6dc2375825c13eeb5c731f49d4f42155e3c34/lib/charms/prometheus_k8s/v0/prometheus_scrape.py#L1862) in cos-agent.

Yes, maybe a public function to change the `metrics_rules_dir`, or allow filtering / selection of rule files in that directory.

> Would you mind elaborating the use case?

We are currently build a COS-native [subordinate charm](https://github.com/canonical/charm-prometheus-hardware-exporter) that exposes the metrics from some hardware components (e.g. RAID cards / NVME / IPMI) via a customized [exporter](https://github.com/canonical/prometheus-hardware-exporter). The exporter contains multiple collectors, and all available collectors enabled by default. But we disable unused collectors via a configuration file. 

In the charm, we are going the write logic to automatically disable the unused collectors based on some conditions (e.g. the existence of RAID card / NVME / IPMI). However, the charm itself contains all the alert rules designed for the collectors. If we are going to disable some collectors, we would also like to "disable" the alert rules that are associated with the collectors. Currently, we don't find a good way to do so since the `metrics_rules_dir` is only set when the `COSAgentProvider` class is initialized. 

> Have you considered [cos-config](https://github.com/canonical/cos-configuration-k8s-operator)?

We feel like the exporter charm should have the alert rules for the metrics it provides, not via an external charm.

**Comment by sed-i** [comment]
> If we are going to disable some collectors, we would also like to "disable" the alert rules that are associated with the collectors.

- Alerts for missing metrics will not fire (unless you have an `absent` guard). Is there a particular reason you'd like to cleanup other than "declogging" the UI?
- How do you feel about having a new regex matcher arg in the constructor?

**Comment by chanchiwai-ray** [comment]
> Alerts for missing metrics will not fire (unless you have an absent guard). Is there a particular reason you'd like to cleanup other than "declogging" the UI?

@sed-i Thanks for the explanation! Coincidentally, after discussion internally with my team, we also have the same conclusion that the alerts with missing metrics will not be fired. In this case, I think the requested feature of "granular control of what alert rules in the `metrics_rules_dir`" maybe put into the "wish list". Of course, having a regex matcher arg in the constructor is also welcome. 

Please feel free to close it if you believe that the request is unimportant to the `COSAgentProvider`. 

Thanks for the help!

**Comment by sed-i** [comment]
Related: https://github.com/canonical/prometheus-k8s-operator/pull/395
