### ISSUE TITLE
"Missing incoming ('requires') relation" is confusing.

### ISSUE THREAD

**Issue by dstathis** [canonical/grafana-agent-k8s-operator#218]
### Bug Description

I saw "Missing incoming ('requires') relation" in a blocked status. I just added random relations until I finally looked in the source code to figure out what it means. This message is not really meaningful.

Additionally "requires" means something completely different for charms.

### To Reproduce

-

### Environment

-

### Relevant log output

```shell
-
```

**Comment by lucabello** [comment]
The message has been improved by explicitly mentioning the relations needed, in https://github.com/canonical/grafana-agent-k8s-operator/pull/286
