### ISSUE TITLE
Support for arm64

### ISSUE THREAD

**Issue by przemeklal** [canonical/grafana-agent-k8s-operator#235]
### Enhancement Proposal

We'd like to be able to monitor arm64 servers, as far as I am aware this architecture is not supported at the moment.

**Comment by sed-i** [comment]
References:
- https://discourse.charmhub.io/t/charmcraft-bases-provider-support/4713
- [Prior art](https://github.com/search?q=org%3Acanonical+language%3Ayaml+architectures+arm64+path%3A**%2Fcharmcraft.yaml&type=code)
  - https://github.com/canonical/openstack-cloud-controller-operator/blob/954e629911c0ff43c3e8f68cbd21e2168165dfab/charmcraft.yaml#L16
  - https://github.com/canonical/charm-lxd-integrator/blob/91af03db79a57a87abfcd683ce42748f54bd32b5/charmcraft.yaml#L9

**Comment by lucabello** [comment]
I believe this has been done here: https://github.com/canonical/grafana-agent-k8s-operator/pull/264
