### ISSUE TITLE
the blocked status for multiple principals is cleared, likely by update-status

### ISSUE THREAD

**Issue by simskij** [canonical/grafana-agent-k8s-operator#236]
### Bug Description

see title. happens for the machine charm.

### To Reproduce

1. juju deploy ubuntu --base ubuntu@22.04
2. juju deploy grafana-agent --channel edge ga
3. juju deploy hardware-observer --channel edge hw
4. juju relate ubuntu ga
5. juju relate ubuntu hw
6. juju relate ga hw
7. juju status --relations --watch 1s

### Environment

lxd, machine charm, juju 3.2.0

### Relevant log output

```shell
n/a
```

**Comment by dstathis** [comment]
I can't reproduce this. It has probably been fixed.
