### ISSUE TITLE
Fix logging story for grafana-agent [both]

### ISSUE THREAD

**Issue by dstathis** [canonical/grafana-agent-k8s-operator#248]
### Bug Description

There are a number of issues I have noticed with log alert rules.

* The k8s charm does not ship any of it's own logs but does define alert rules. It should either send it's own logs or not send the alert rules.
* For the machine charm, logs have inconsistent labels. The built in jobs seem to define app, model, model_uuid, and unit while the snap based jobs define job, model, and model_uuid.
* For the machine charm, (and for k8s but it is not relevant), juju_charm is defined in alert expressions but will not be present for logs since there is no way to get the charm name of a remote unit.
* For the machine charm, alert rules use the topology of grafana-agent while logs have the topology of the principal.

### To Reproduce

1. Deploy grafana-agent-k8s
2. Relate to COS
3. Observe logs and rules
4. Deploy grafana-agent and zookeeper and relate them
5. Relate to COS
6. Observe logs and rules

### Environment

```
┌──────────────┬────────────────────────────────────────────────────┐
│ jhack        │ 0.3.18.3                                           │
│ python       │ 3.10.12 (/home/dylan/repos/jhack/venv/bin/python3) │
│ juju-* snaps │  juju │ 3.1.5 - 23354 (latest/stable)              │
│ microk8s     │ MicroK8s v1.27.5 revision 5891                     │
│ lxd          │ 5.17                                               │
│ multipass    │ Not Installed.                                     │
│ multipassd   │ Not Installed.                                     │
│ os           │ Ubuntu 22.04.3 LTS                                 │
│ kernel       │ Linux 5.15.0-83-generic x86_64                     │
└──────────────┴────────────────────────────────────────────────────┘
```

### Relevant log output

```shell
-
```

**Comment by lucabello** [comment]
@dstathis @sed-i I believe this is not relevant anymore, can any of you confirm?

**Comment by sed-i** [comment]
Seems outdated. Closing.
The charm is used in prod so we'd hear about if it was still an issue.
Please re-open if I'm missing something.
