### ISSUE TITLE
Disable upstream analytics

### ISSUE THREAD

**Issue by slapcat** [canonical/grafana-agent-k8s-operator#295]
### Bug Description

Logs are flooded with failure messages regarding [upstream analytics](https://grafana.com/docs/loki/latest/configure/#analytics):

```
msg="failed to send usage report" retries=0 err="Post \"https://stats.grafana.org/agent-usage-report\": context deadline exceeded
```

See also: https://github.com/grafana/loki/issues/10648

### To Reproduce

1. Deploy grafana-agent charm.
2. Relate to compatible machine charm.
3. Watch `/var/log/syslog` for error.

### Environment

Grafana-agent is related to machine charms in an openstack cloud.

### Relevant log output

```shell
msg="failed to send usage report" retries=0 err="Post \"https://stats.grafana.org/agent-usage-report\": context deadline exceeded
```

**Comment by lucabello** [comment]
We have a few duplicates of this issue, so I'm closing this one in favor of #266.
