### ISSUE TITLE
Refactor Grafana agent config generation.

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/grafana-agent-k8s-operator#36]
This issue is related to #34.

The config file is built on pebble_ready and completed once you relate grafana agent with loki.

We're saving the configuration in stored because if you have a grafana agent and loki charms related, when you reboot the VM in which microk8s is running, the `loki_push_api_endpoint_joined` is not fired again and the config will be in a different state (without loki section)

The safest way to make this work is to have a method that builds the whole config file and call it in both `pebble_ready` and `relation_joined`. The method can simply exit if resources are not yet ready and it will be called when the second hook fires.

This is better is we have all the information needed to construct the config file statelessly and added a stored state introduces another moving part which could introduce bugs.

**Comment by dstathis** [comment]
I believe this has been done already. Reopen if you think it still needs work.
