### ISSUE TITLE
Password shown on action changes after scaling

### ISSUE THREAD

**Issue by zmraul** [canonical/grafana-agent-k8s-operator#37]
Hello!

After deploying the cos-lite bundle:
```bash
juju add-model cos
juju deploy cos-lite --channel=edge --trust
```
I can get the dashboard password with:
```
juju run-action grafana get-admin-password
```

If I scale down the grafana app with:
```
juju remove-unit grafana --num-units 1
```
and then scale it back up:
```
juju add-unit grafana --num-units 1
```

Using `get-admin-password` shows a different one, but the dashboard is accessible with the old one.

**Comment by Abuelodelanada** [comment]
Hola Raúl,

As far as I understand this is a grafana issue, not a Grafana agent one.
Please fill a bur here: https://github.com/canonical/grafana-k8s-operator/issues
