### ISSUE TITLE
Container push and pull is now supported by harness. Replace mocks

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/grafana-agent-k8s-operator#45]
Container push and pull is now supported by harness, see e.g. https://github.com/canonical/grafana-agent-k8s-operator/pull/17/commits/621103cb14fa759dce2ee87bca28e1274241c3ae

_Originally posted by @mmanciop in https://github.com/canonical/grafana-agent-k8s-operator/pull/44#discussion_r845510984_

**Comment by Abuelodelanada** [comment]
@mmanciop said:

> For evidence, these mocks have hidden this bug all along https://github.com/canonical/loki-k8s-operator/pull/138

See https://github.com/canonical/grafana-agent-k8s-operator/pull/44#discussion_r846085904

**Comment by mmanciop** [comment]
I have already done it in #17
