### ISSUE TITLE
Replace kubernetes_service.py with the observability_libs equivalent

### ISSUE THREAD

**Issue by simskij** [canonical/grafana-agent-k8s-operator#68]
### Enhancement Proposal

Replace kubernetes_service.py with the observability_libs equivalent

**Comment by simskij** [comment]
@lucabello seems like you've already switched out the local file in favor of the lib. can you please delete the file from the src folder as well so we can close this?

**Comment by lucabello** [comment]
The v0 file of `kubernetes_service_patch.py` had already been deleted a long time ago, even with charms using it, hence why I was pressed to update them to v1 :)
Closing this ticket!

**Comment by lucabello** [comment]
Oh nevermind, you meant in this repo: will do!
