### ISSUE TITLE
Missing relation in the charm based on the INTEGRATION documentation

### ISSUE THREAD

**Issue by Barteus** [canonical/grafana-agent-k8s-operator#87]
### Bug Description

The relation is present in the documentation of INTEGRATION but there is no implementation in the charm (yet).
It would be awesome to have it done or marked in the documentation that it is expected to start version xx.yy

### To Reproduce

1. Install microk8s and install cos-lite on top of it
2. Install Charmed Kubernetes separately 
3. Create cross model relation between grafana-agent-k8s and grafana-k8s

### Environment

I ran it using Mk8s on LXD with COS lite and Charmed Kubeflow on bare-metal. The grafana-agent-k8s charm was deployed on CK8s. 

### Relevant log output

```shell
$ juju add-relation admin/cos-kubeflow.grafana-dashboards grafana-agent-k8s:grafana-dashboard
ERROR application "grafana-agent-k8s" has no "grafana-dashboard" relation

$ juju status grafana-agent-k8s
Model     Controller        Cloud/Region  Version  SLA          Timestamp
kubeflow  foundations-maas  ck8s/default  2.9.37   unsupported  07:49:56Z

SAAS                             Status  Store             URL
grafana-dashboards               active  foundations-maas  admin/cos-kubeflow.grafana-dashboards
prometheus-receive-remote-write  active  foundations-maas  admin/cos-kubeflow.prometheus-receive-remote-write

App                Version  Status  Scale  Charm              Channel  Rev  Address         Exposed  Message
grafana-agent-k8s  0.26.1   active      1  grafana-agent-k8s  stable    24  122.33.123.123  no       

Unit                  Workload  Agent  Address         Ports  Message
grafana-agent-k8s/0*  active    idle   123.123.123.123
```

**Comment by simskij** [comment]
The solution here should be to implement the `grafana-dashboard` relation in `grafana-agent`. This can't be done using the existing library, as that also mutates the dashboards. Either we create a simple library for shuffling the dashboard data over as-is, or if we expect this to be the only place where we need to this, do it directly in the charm.
